USE [master]
GO

/****** Object:  Database [obiee_book]    Script Date: 27/03/2016 11:03:35 ******/
CREATE DATABASE [obiee_book]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'obiee_book', FILENAME = N'C:\apps\mssql\MSSQL13.MSSQLSERVER\MSSQL\DATA\obiee_book.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'obiee_book_log', FILENAME = N'C:\apps\mssql\MSSQL13.MSSQLSERVER\MSSQL\DATA\obiee_book_log.ldf' , SIZE = 139264KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [obiee_book] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [obiee_book].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [obiee_book] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [obiee_book] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [obiee_book] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [obiee_book] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [obiee_book] SET ARITHABORT OFF 
GO

ALTER DATABASE [obiee_book] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [obiee_book] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [obiee_book] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [obiee_book] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [obiee_book] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [obiee_book] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [obiee_book] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [obiee_book] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [obiee_book] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [obiee_book] SET  DISABLE_BROKER 
GO

ALTER DATABASE [obiee_book] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [obiee_book] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [obiee_book] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [obiee_book] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO

ALTER DATABASE [obiee_book] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [obiee_book] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [obiee_book] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [obiee_book] SET RECOVERY FULL 
GO

ALTER DATABASE [obiee_book] SET  MULTI_USER 
GO

ALTER DATABASE [obiee_book] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [obiee_book] SET DB_CHAINING OFF 
GO

ALTER DATABASE [obiee_book] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [obiee_book] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [obiee_book] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [obiee_book] SET QUERY_STORE = OFF
GO

ALTER DATABASE [obiee_book] SET  READ_WRITE 
GO


